name: Deploy to Azure ACI

on:
  push:
    branches:
      - main  # adapte selon ta branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      run: az acr login --name yassineregistrykhalili

    - name: Build Docker image
      run: docker build -t yassineregistrykhalili.azurecr.io/yassine-app:v1 .

    - name: Push Docker image to ACR
      run: docker push yassineregistrykhalili.azurecr.io/yassine-app:v1

    - name: Deploy to Azure Container Instance
      run: |
        az container create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --name yassine-aci-khalili \
          --image yassineregistrykhalili.azurecr.io/yassine-app:v1 \
          --ip-address public \
          --os-type Linux \
          --ports 80 \
          --cpu 1 --memory 1.5 \
          --registry-login-server yassineregistrykhalili.azurecr.io \
          --registry-username ${{ secrets.AZURE_ACR_USERNAME }} \
          --registry-password ${{ secrets.AZURE_ACR_PASSWORD }} \
          --location ${{ secrets.ACI_REGION }} \
          --restart-policy Always

